# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:06
from __future__ import unicode_literals

from django.db import migrations


SQL = """
CREATE INDEX CONCURRENTLY values_value_field_string_value
ON values_value(contact_field_id, UPPER(string_value))
WHERE contact_field_id IS NOT NULL;
"""


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('values', '0009_install_indexes'),
    ]

    operations = [
        migrations.RunSQL(SQL)
    ]
